# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\phili\Desktop\Python\Jeu_des_Capitales_3.0\gui\ui\end_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1000, 600)
        self.score_label = QtWidgets.QLabel(Dialog)
        self.score_label.setGeometry(QtCore.QRect(180, 140, 620, 130))
        font = QtGui.QFont()
        font.setFamily("Programme Bold")
        font.setPointSize(30)
        font.setBold(False)
        font.setWeight(50)
        self.score_label.setFont(font)
        self.score_label.setText("")
        self.score_label.setAlignment(QtCore.Qt.AlignCenter)
        self.score_label.setObjectName("score_label")
        self.rejouerButton = QtWidgets.QPushButton(Dialog)
        self.rejouerButton.setGeometry(QtCore.QRect(380, 330, 200, 50))
        font = QtGui.QFont()
        font.setFamily("Programme Bold")
        font.setPointSize(12)
        self.rejouerButton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\phili\\Desktop\\Python\\Jeu_des_Capitales_3.0\\gui\\ui\\../assets/rejouer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rejouerButton.setIcon(icon)
        self.rejouerButton.setObjectName("rejouerButton")
        self.percentage_label = QtWidgets.QLabel(Dialog)
        self.percentage_label.setGeometry(QtCore.QRect(250, 260, 481, 40))
        font = QtGui.QFont()
        font.setFamily("Programme Regular")
        font.setPointSize(12)
        self.percentage_label.setFont(font)
        self.percentage_label.setText("")
        self.percentage_label.setAlignment(QtCore.Qt.AlignCenter)
        self.percentage_label.setObjectName("percentage_label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.rejouerButton.setText(_translate("Dialog", " Rejouer"))
