# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\phili\Desktop\Python\Jeu_des_Capitales_3.0\gui\ui\main_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1000, 600)
        Dialog.setMinimumSize(QtCore.QSize(1000, 600))
        Dialog.setMaximumSize(QtCore.QSize(1000, 600))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        Dialog.setFont(font)
        Dialog.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.playButton = QtWidgets.QPushButton(Dialog)
        self.playButton.setGeometry(QtCore.QRect(420, 370, 160, 50))
        font = QtGui.QFont()
        font.setFamily("Programme")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.playButton.setFont(font)
        self.playButton.setObjectName("playButton")
        self.title = QtWidgets.QLabel(Dialog)
        self.title.setGeometry(QtCore.QRect(320, 300, 350, 50))
        font = QtGui.QFont()
        font.setFamily("Programme Bold")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.title.setFont(font)
        self.title.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.title.setMouseTracking(False)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.Img = QtWidgets.QLabel(Dialog)
        self.Img.setGeometry(QtCore.QRect(400, 80, 200, 201))
        self.Img.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Img.setText("")
        self.Img.setPixmap(QtGui.QPixmap("c:\\Users\\phili\\Desktop\\Python\\Jeu_des_Capitales_3.0\\gui\\ui\\../assets/map.png"))
        self.Img.setScaledContents(True)
        self.Img.setWordWrap(False)
        self.Img.setObjectName("Img")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.playButton.setText(_translate("Dialog", "Jouer"))
        self.title.setText(_translate("Dialog", "Jeu des Capitales"))
